apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ahmed.abdi67@outlook.com
    privateKeySecretRef:
      name: issuer
    solvers:
      - dns01:
          route53:
            region: eu-west-2
            hostedZoneID: Z103935430WUS287YMWJ6 
            